In [ ]:
# Autor: Josias Dominguez Hernández
# Metodos Numericos

import numpy as np

n = int(input("No. Columnas\n"))
col = []
col3=[]
for i in range(n):
    row = []
    row2=[]
    for j in range(0,n+1):
        print("[",i,j,"] >>")
        t = float(input("Valor:"))
        row.append(t)
        row2.append(t)
    col.append(row)
    col3.append(row2)
A = np.matrix(col)
Z= np.matrix(col3)
print("\nMatriz \n")
print(A)


for i in range(n):
    for j in range(n):
        A[i,:] = A[i,:]/A[i,i]
        if i != j:
            factor = A[j,i]/A[i,i]
            for k in range(n+1):
                A[j,k]=A[j,k]-factor*A[i,k]
      

print("Gauss\n")
print(A)

print("RESULTADOS\n")
print(A[:,n])


No. Columnas
3
[ 0 0 ] >>
Valor:3
[ 0 1 ] >>
Valor:-1
[ 0 2 ] >>
Valor:1
[ 0 3 ] >>
Valor:12
[ 1 0 ] >>
Valor:0.5
[ 1 1 ] >>
Valor:5
[ 1 2 ] >>
Valor:-0.25
[ 1 3 ] >>
Valor:10
[ 2 0 ] >>
Valor:0.1
[ 2 1 ] >>
Valor:0.2
[ 2 2 ] >>
Valor:7
[ 2 3 ] >>
Valor:14

Matriz 

[[ 3.   -1.    1.   12.  ]
 [ 0.5   5.   -0.25 10.  ]
 [ 0.1   0.2   7.   14.  ]]
Gauss

[[1.         0.         0.         3.9353498 ]
 [0.         1.         0.         1.70122374]
 [0.         0.         1.         1.89517432]]
RESULTADOS

[[3.9353498 ]
 [1.70122374]
 [1.89517432]]


0

In [ ]:
# Multiplicacion 
a1 = np.array([[3,-1,1],[0.5,5,-0.25],[0.1,0.2,7]])
solucion = np.matmul(a1,A[:,n])

print(solucion)

[[12.]
 [10.]
 [14.]]
